export default {
  staff_email: "/staffs/staff_email",
  staff_logout: "/staffs/staff_logout",
  clients: "/clients",
  client_create: "/clients/create",
  client_update: "/clients/update",
  company_create: "/companies/create",
  clients_delete: "/clients/delete",
  companies: "/companies",
  companies_delete: "/companies/delete",
  juristic_types: "/juristic_types",
  client_companies: "/companies/client_companies",
  rebind_companies_to_client: "/clients_companies/rebind_companies_to_client",
  company_update: "/companies/update",
  company_clients: "/companies/company_clients",
  rebind_clients_to_company: "/clients_companies/rebind_clients_to_company",
  client_email: "/clients/client_email",
  client_logout: "/clients/client_logout",
  clients_companies: "/clients/companies"
}